### ISSUE TITLE
Is it possible to load existing (already uploaded) files to Dropzone?

### ISSUE THREAD

**Issue by Tzvetelin88** [fortana-co/react-dropzone-uploader#102]
If I have files uploaded to S3 (or other) can I load them to Dropzone and then do edit like, delete, upload new ones etc.

Thanks!

**Comment by milankyada** [comment]
Hey @Tzvetelin88 did you get the solution for this?
I tried with `initialFiles` and it's not working for me

**Comment by milankyada** [comment]
@Tzvetelin88 nevermind, I have figured it out.

**Comment by Tzvetelin88** [comment]
> @Tzvetelin88 nevermind, I have figured it out.

Can you please share how did you solve this?
Thanks!

**Comment by milankyada** [comment]
Hi @Tzvetelin88 ,
you'll need to make the object of file array and assign it to `initialFiles` 
Here is an example you can follow,
I have images uploaded under `uploads/id/image.jpeg`

```
let temp = ["uploads/2/f26yVL2ayLGrbwXPR7T37C4sMQ9IIjhYkCASOMq6.jpeg"];
let ss = [];
let obj = {...this.state.objectURL};

                    temp.forEach(function(i,k){
                        let fileName = "http://127.0.0.1:8000/storage/"+i;
                        fetch(fileName).then(res => {
                            res.arrayBuffer().then(buf => {
                                ss.push(new File([buf], i, { type: 'image/jpge'}))
                            })
                        })
                    })
this.setState({objectURL: ss});
<Dropzone
initialFiles = {this.state.objectURL}
/>
```

**Comment by Tzvetelin88** [comment]
initialFiles  - is uploading files automatically yes? In this case we are loading files and also uploading them again to the server? If yes, is it possible not to upload them again?

**Comment by milankyada** [comment]
You're just loading file with initialFiles, but it's upto you how you handle the form submit, there's a function to detect what is changed in dropzone(like file added/removed) you can use that to detect the change.
Here is the example given. [onChangeStatus](https://react-dropzone-uploader.js.org/docs/examples)

you'll have to follow this example

**Comment by zsolt-dev** [comment]
There are multiple issues(#102, #73, #36) asking about the same functionality: how to edit the form without downloading and uploading everything on each submit, or even worse, each view.

I think the solution could be passing an array of objects to initialFiles that would tell RDU the list of files with some metadata, that these files are already uploaded and not to download or upload them again.

The solution for me know will be probably this:
1. use RDU for uploading only. After upload is finished, I will remove the file from RDU.
2. implement own file previews with own file removal via custom API so no files will not need to be download for each view, just some metadata from the API

**Comment by Tzvetelin88** [comment]
Yes, I have done it in the same way few weeks ago.
RDU to upload and I've created a custom File component to preview / download/ remove them.

**Comment by cordial** [comment]
@Tzvetelin88 any chance you can share this example? I have a similar issue

**Comment by cordial** [comment]
Or @zsolt-dev
