### ISSUE TITLE
Override upload button

### ISSUE THREAD

**Issue by gerhardcit** [fortana-co/react-dropzone-uploader#14]
I'm struggling to override the uploader with my own upload button on a mobi design.

Is there a change you can create mobi samples where the input:type=[file] is handled in this way?
https://reactjs.org/blog/2018/03/29/react-v-16-3.html#createref-api

In mobile design you typically only have a camera button and it get's very specifically styled by the designers.

**Comment by kylebebak** [comment]
@gerhardcit 

Hey Gerhard. I'm not sure whether you want to override `SubmitButton` or `Input` -- I'm guessing `Input`.

RDU uses [component injection](https://react-dropzone-uploader.js.org/docs/customization#component-injection) to let you totally override the file `Preview`, the `Input`, the `SubmitButton`, or the entire `Layout` of the dropzone.

Here are live examples for overriding [Preview](https://react-dropzone-uploader.js.org/docs/examples#!/Custom%20Preview) and [Layout](https://react-dropzone-uploader.js.org/docs/examples#!/Custom%20Layout).

If you want your own Input, you can do something like the following. If you paste this code into any of the [code input areas in the examples page](https://react-dropzone-uploader.js.org/docs/examples) you can see how it works live.

```js
const MyInput = ({ accept, onFiles, files }) => {
  const text = files.length > 0 ? 'Add more files' : 'Choose files'

  return (
    <label style={{ backgroundColor: '#007bff', color: '#fff', cursor: 'pointer', padding: 15, borderRadius: 3 }}>
      {text}
      <input
        style={{ display: 'none' }}
        type="file"
        accept={accept}
        multiple
        onChange={e => {
          onFiles(getDataTransferItems(e))
          e.target.value = null
        }}
      />
    </label>
  )
}

const MyDropzone = () => {
  const handleSubmit = (files, allFiles) => {
    console.log(files.map(f => f.meta))
    allFiles.forEach(f => f.remove())
  }

  return (
    <Dropzone
      getUploadParams={() => ({ url: 'https://httpbin.org/post' })}
      onSubmit={handleSubmit}
      InputComponent={MyInput}
    />
  )
}

<MyDropzone />
```

If you want to see all the props passed to `MyInput`, just look at the default `Input` component: <https://github.com/fortana-co/react-dropzone-uploader/blob/master/src/Input.js>.

I'll leave this open for a few days. If this solves your problem let me know!

**Comment by kylebebak** [comment]
Also, I'll soon be releasing a version that exports `getFilesFromEvent`, which means you could write 

`onChange={e => { onFiles(getFilesFromEvent(e)) }}`

instead of

`onChange={e => { onFiles(Array.prototype.slice.call(e.target.files)) }}`

This function can handle change events for an input or drop events for a `div`, `p`, etc.

**Comment by kylebebak** [comment]
Ok, `getFilesFromEvent` now exported in `2.9.0`. See here for [live example of custom Input component](https://react-dropzone-uploader.js.org/docs/examples#!/Custom%20Input).

@gerhardcit 
Closing, if you have any trouble let me know.
