### ISSUE TITLE
Synthetic event error

### ISSUE THREAD

**Issue by Stardog** [fortana-co/react-dropzone-uploader#16]
In version 2.10 I am experiencing the following warning when I try to select an image for upload:

`Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.`

`Uncaught (in promise) TypeError: Cannot set property 'value' of null
    at react-dropzone-uploader.umd.js:14
    at w (react-dropzone-uploader.umd.js:1)
    at Generator.c._invoke (react-dropzone-uploader.umd.js:1)
    at Generator.e.(:3000/canopy/carouse…/anonymous function) [as next] (http://localhost:3000/canopy/mod/carousel/javascript/dev/vendor.js:32620:9979)
    at s (react-dropzone-uploader.umd.js:1)
    at a (react-dropzone-uploader.umd.js:1)`

This error can occurs in my code and in the quick start code from the readme. It appears immediately after the handChangeStatus function with the "preparing" status. It does not appear in 2.8.1.

I am still able to upload the image successfully.

**Comment by kylebebak** [comment]
@Stardog 

Sorry I didn't get a chance to look at this until now. Work has been crazy, but this month I've got more free time and a colleague and I are going to make some improvements to the library, including fixing this issue.

Thanks for reporting it!

**Comment by g-bar** [comment]
This issue has been solved in the latest version (2.10.1).
