### ISSUE TITLE
Option to disable forceUpdate

### ISSUE THREAD

**Issue by peitalin** [fortana-co/react-dropzone-uploader#39]
Having forceUpdate throughout the Dropzone uploader makes it difficult to prevent re-renders in subcomponents.

For a custom dropzone layout,  adding items will cause the entire layout (and all upload previews) to re-render, and this can't be prevented easily with shouldComponentUpdate or React.memo.

Is there a way to disable this.forceUpdate?
e.g: this line :
```
  forceUpdate = () => {
    if (this.mounted) super.forceUpdate()
  }
```

**Comment by maryam-mokhtari** [comment]
Did you find any solution?
Actually I want the parent component to rerender after `onSubmit` is called.

**Comment by zanedev** [comment]
Running into this also in various ways, it re-renders the preview over and over and can't stop it.  Any solution to stop the re-render?

![dnduploaderflashing](https://user-images.githubusercontent.com/817344/80317026-2e5f0c00-87b6-11ea-8f32-5c3e23813312.gif)
