### ISSUE TITLE
Upload file onsubmit

### ISSUE THREAD

**Issue by yudataguy** [fortana-co/react-dropzone-uploader#51]
I've set autoUpload={false} to prevent auto upload when files dropped. But couldn't find a way to have file upload started onSubmit. Since the submit button is disabled if the file is header doesn't have the status 'headers_received' or 'done'. Any suggestion on how to get it working correctly?

**Comment by manrajesh** [comment]
Did you find a way to do this?

**Comment by manrajesh** [comment]
This how i figured it out
1)set `autoUpload={false}`
2)enable Submit button by 
`if(status === 'ready'){
        meta.status = 'headers_received'
      }`

in `handleChangeStatus`

3)call restart on submit click

`handleSubmit = (files, allFiles) => {
      allFiles.forEach(f => f.restart())
    }`

**Comment by yudataguy** [comment]
We tried a different approach. 
1) set ```autoUpload={false}```
2) have a ```handleSubmit``` button onClick function with customized ```SubmitButtonComponent={SubmitButton}```
3) build a ```uploadImage()``` for handling image upload
4)  in handleSubmit
```
allFiles.forEach(f => {
      uploadImage(f.file);
    }) 
```
Maybe I'll try your method to see if this can work.

**Comment by zarandonlautaro** [comment]
> We tried a different approach.
> 
> 1. set `autoUpload={false}`
> 2. have a `handleSubmit` button onClick function with customized `SubmitButtonComponent={SubmitButton}`
> 3. build a `uploadImage()` for handling image upload
> 4. in handleSubmit
> 
> ```
> allFiles.forEach(f => {
>       uploadImage(f.file);
>     }) 
> ```
> 
> Maybe I'll try your method to see if this can work.

How do you make this ?

**Comment by MiracelVip** [comment]
Was somebody able to solve the mentioned problem?
