### ISSUE TITLE
Add TypeScript declarations

### ISSUE THREAD

**Issue by kylebebak** [fortana-co/react-dropzone-uploader#7]

**Comment by kevotovar** [comment]
Hi @kylebebak!  Can I take this issue?

**Comment by kylebebak** [comment]
Hey @kevotovar !

[I added instructions](https://github.com/fortana-co/react-dropzone-uploader#running-dev) to the README for running dev.

Fork the repo, run dev, and get a feeling for the code base. The prop types are documented in the code, [and also here](https://react-dropzone-uploader.js.org/docs/props).

I think this is a good time to work on TS annotations, because the API for RDU is pretty stable now.

**Comment by nchen63** [comment]
Ugh, I didn't realize that there already was a feature branch for the typings https://github.com/fortana-co/react-dropzone-uploader/tree/feature/typescript

**Comment by kylebebak** [comment]
@nchen63 
That feature branch has some exploratory junk, but nothing usable... So your efforts were definitely not in vain!

In the last few days I actually started working on an `index.d.ts` as well, in master. I'll take your type declarations, add them to what I've got, and push a release with TypeScript support within the next week =)

I was thinking I'd change `examples/src/index.js`, which is the entry file for webpack-dev-server, and change it to `index.ts`.

In `package.json` I could change `"dev": "webpack-dev-server ...",` to `"dev": "tsc && webpack-dev-server ...",`, so that running dev `tsc` to compile `index.ts` without errors, as a cheap shortcut for testing the type declarations. Any thoughts?

**Comment by kylebebak** [comment]
[TS declarations](https://github.com/fortana-co/react-dropzone-uploader/blob/master/src/Dropzone.d.ts) ship with `2.8.0`. They're tested against the code in <https://github.com/fortana-co/react-dropzone-uploader/blob/master/examples/src/index.tsx>.

@nchen63 
I took your definitions and added to them. Thanks again!
