### ISSUE TITLE
Cannot add styles

### ISSUE THREAD

**Issue by gil-air-may** [fortana-co/react-dropzone-uploader#8]
Hello, I am trying to style the `Dropzone` component. But no matter what I try, the Dropzone component does not change its appearance. It stays default.

At the top of React component I have

`import classes from "./IdeaForm.module.css";`

...and inside the render method

```
        <Dropzone
          addClassNames={classes.Dropzone}
          getUploadParams={this.getUploadParams}
          onChangeStatus={this.handleChangeStatus}
          onSubmit={this.handleSubmit}
          accept="image/*,audio/*,video/*"
        />
```

I have also tried without using CSS modules, but it didn't work.

My IdeaForm.module.css file: 

```
.Dropzone{
  color: black;
  width: 200px;
  border-style: none;
}
```
I have imported the styles for RDU on the root component, as suggested by the docs. On top of `index.js` I have:

`import "react-dropzone-uploader/dist/styles.css";` 

I have tried the three latest versions, and did not manage to add the style.

I have also tried with the `className` prop (instead of the addClassNames). But no results.
Same thing with the style prop.

Any help is greatly appreciated.

**Comment by kylebebak** [comment]
Hey there!

The `styles`, `classNames` and `addClassNames` props should all be object literals, not strings.

Change your code to something like this:

```
<Dropzone
  addClassNames={{ dropzone: classes.Dropzone }}
  getUploadParams={this.getUploadParams}
  onChangeStatus={this.handleChangeStatus}
  onSubmit={this.handleSubmit}
  accept="image/*,audio/*,video/*"
/>
```

Basically, these object literals let you override many different styles in RDU with just one prop. For example, if you wanted to override the style of the dropzone when it's active, when files are being rejected, and when it's disabled, you could do something like this:

```
<Dropzone
  addClassNames={{
    dropzoneActive: classes.DropzoneActive,
    dropzoneReject: classes.DropzoneReject,
    dropzoneDisabled: classes.DropzoneDisabled,
  }}
  getUploadParams={this.getUploadParams}
  onChangeStatus={this.handleChangeStatus}
  onSubmit={this.handleSubmit}
  accept="image/*,audio/*,video/*"
/>
```

Let me know if this helps.

**Comment by gil-air-may** [comment]
Gotcha! Thanks a lot!

**Comment by kylebebak** [comment]
If you have any more trouble with this let me know. I'm going to close this.
