### ISSUE TITLE
Send audio to server 

### ISSUE THREAD

**Issue by whiteRa2bit** [fortana-co/react-dropzone-uploader#80]
Can you please explain how can I send an uploaded audio to sever? Thank you in advance!

**Comment by hochan222** [comment]
The question is not clear.
```
getUploadParams={({ file, meta: { name } }) => ({
  url:  'http://93.175.9.142:3999/send_mp3/',
  method: 'POST',
})}
accept="image/*,audio/*,video/*"
```
this options will help you!

https://react-dropzone-uploader.js.org/docs/examples
